### ISSUE TITLE
config v20190319  has a problem

### ISSUE THREAD

**Issue by LittleStardust** [150balbes/Amlogic_s905-kernel#10]
When I compile kernel with "config v20190319" , it will report an error:" ‘kernel/config_data.gz’  need a target ‘.config’ ". It can be solved by choose "Kernel  .config support".

**Comment by 150balbes** [comment]
It is not clear that do not work. Write detailed steps.

**Comment by LittleStardust** [comment]
1.make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- menuconfig
    then load config(v20190319)
2.make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu-
    it has reported an error:
            make[1]: *** 没有规则可制作目标“.config”，由“kernel/config_data.gz” 需求。 停止。
            Makefile:1043: recipe for target 'kernel' failed
            make: *** [kernel] Error 2
    It means need ".config support".

Solution:
    It can be solved by chose   "General setup" -> "kernel  .config support".
    `<*> kernel  .config support`
