### ISSUE TITLE
Monitor not working

### ISSUE THREAD

**Issue by moham96** [150balbes/Amlogic_s905-kernel#11]
Hi,
I tried the master branch of this repo using the config from your armbian repo:
https://github.com/150balbes/Build-Armbian/blob/master/config/kernel/linux-aml-s905-dev.config
and I don't get output through HDMI
The /dev/dri/card0 exists but the screen is not detecting a signal.
testing the mainline torvalds tree works fine and i get output through HDMI.

My device is KII pro and I use the meson_gxbb_p201.dtb

**Comment by 150balbes** [comment]
Hi
The "dev" configuration is for a different kernel.
