### ISSUE TITLE
boot from internal mmc

### ISSUE THREAD

**Issue by gcsuri** [150balbes/Amlogic_s905-kernel#12]
Hi 150balbes,

 could you enable the following config options to the kernel, please?
CONFIG_BLK_CMDLINE_PARSER=y
CONFIG_CMDLINE_PARTITION=y
CONFIG_MTD_CMDLINE_PARTS=y
So with this options there can be boot the box from internal mmc with the old partition layout.
example: blkdevparts=mmcblk1:0x0800000@0x027400000(env),0x0800000@0x02e400000(dtb),0x02000000@0x034400000(boot),0x080000000@0x036c00000(swap),0x02eca00000@0x0b7400000(data) root=/dev/mmcblk1p5 ...

thanks you
best regards, Gabor

**Comment by gcsuri** [comment]
ps: sorry I wanted to write it into the build-armbian repo...

**Comment by 150balbes** [comment]
> CONFIG_CMDLINE_PARTITION=y

This option is not detected.

**Comment by gcsuri** [comment]
Hi 150balbes,

CONFIG_PARTITION_ADVANCED=y
CONFIG_CMDLINE_PARTITION=y
are needed for booting from cmdline defined mtd device.
Thank you, Gabor

**Comment by gcsuri** [comment]
means CONFIG_PARTITION_ADVANCED=y is needed to detect CONFIG_CMDLINE_PARTITION=y
