### ISSUE TITLE
Hello, can you provide a branch to support the real-time kernel?

### ISSUE THREAD

**Issue by mlyq111** [150balbes/Amlogic_s905-kernel#13]
Hello, can you provide a branch to support the real-time kernel?

**Comment by mlyq111** [comment]
I tried to recompile with the PREEMPT_RT patch, but I never succeeded.

**Comment by 150balbes** [comment]
> can you provide a branch to support the real-time kernel?

For what purpose do you need it ?

**Comment by mlyq111** [comment]
Thank you for your reply. If you can, tailor it to dietpi and install squeezelite as the simplest playback terminal.
