### ISSUE TITLE
could you add  NFS Kernel module ?

### ISSUE THREAD

**Issue by wangyu1314** [150balbes/Amlogic_s905-kernel#15]
Hello.
the kernel is very great, but we need the nfs kernel module in phicomm-n1 box, can you complex it within to 5.1 kernel ?
thank you.

**Comment by 150balbes** [comment]
Hi
Specify kernel options for the configuration.

**Comment by wangyu1314** [comment]
Thank you for your reply. I found the 4.86 have compiled the nfs moudles in kernel.
