### ISSUE TITLE
The wired network is not available

### ISSUE THREAD

**Issue by myeveryheart** [150balbes/Amlogic_s905-kernel#16]
Hi, I use
Armbian_5.87_Aml-s905_Debian_buster_default_5.1.0_desktop_20190521 + phicomm-n1
It seems that the wired network is not available but wireless is fine.

**Comment by 150balbes** [comment]
Hi
This DTB was provided by another user. According to his information, everything worked for him. I don't have that kind of equipment, I don't know what the reason is.

**Comment by myeveryheart** [comment]
Hi, the 'another user'  is @yangxuan8282   ?

**Comment by 150balbes** [comment]
He may be, but I don't remember.

**Comment by myeveryheart** [comment]
ok, thank you, I will contact him.
