### ISSUE TITLE
Android serial pl2303.ko or ch341.ko 

### ISSUE THREAD

**Issue by araczkowski** [150balbes/Amlogic_s905-kernel#20]
sorry if this question is off topic
I'm looking for the way to compile the Android driver module (.ko) for this SOC (Amlogic 905)
Can you recommend a proper way to do this please?
Do you have a kernel source from Amlogic and proper toolchain to do this?

Thanks in advance :)

**Comment by 150balbes** [comment]
I don't do the Androids.

**Comment by araczkowski** [comment]
> I don't do the Androids.

lucky you ;) 

I see, it is pure Linux kernel for S905, nice and interesting
Thanks for the answer!
