### ISSUE TITLE
Source for the old kernel khadas-3.14

### ISSUE THREAD

**Issue by tecufanujacu** [150balbes/Amlogic_s905-kernel#21]
Please, could you provide the source for the old kernel khadas-3.14? I need it and with a
git clone -b khadas-3.14  https://github.com/150balbes/Amlogic_s905-kernel.git
I'm not more able to get it.
Where can I find it? I used it in the past from your repo but I haven't saved it.

Thanks a lot.

**Comment by 150balbes** [comment]
There are no such sources anymore.

**Comment by tecufanujacu** [comment]
Haven't you any backup to upload somewhere? Please, I really need it.
