### ISSUE TITLE
Is it possible to add an ARM mali GPU driver to the kernel

### ISSUE THREAD

**Issue by rongi5** [150balbes/Amlogic_s905-kernel#23]
Is it possible to add an ARM mali GPU driver to the kernel

**Comment by 150balbes** [comment]
It's already there (Lima and Panfrost)

**Comment by probonopd** [comment]
Hi @150balbes thank you for your great work.

I am trying to build my own OS images, but I can't get Xorg to work. Probably because I am missing some of your packages. Is there a `sources.list` file that you are using to produce your OS images?

Reference:
https://github.com/probonopd/aarch64-squashfs-builder/issues/3

**Comment by koolwiki** [comment]
> It's already there (Lima and Panfrost)

Could you please build a OS image with the ARM mali GPU driver included? Thank you.

**Comment by probonopd** [comment]
Isn't ARM mali GPU driver = Lima and Panfrost driver?
So it's already there...

**Comment by 150balbes** [comment]
> Could you please build a OS image with the ARM mali GPU driver included? Thank you.

This is a private driver (a private BLOB is used) I don't work with him.

> Isn't ARM mali GPU driver = Lima and Panfrost driver?
> So it's already there...

LIMA Panfrost Mali are different drivers.

**Comment by probonopd** [comment]
> This is a private driver (a private BLOB is used) I don't work with him.

I understand. Do you know whether its performance when playing back video in the web browser is better?

**Comment by koolwiki** [comment]
> > Could you please build a OS image with the ARM mali GPU driver included? Thank you.
> 
> This is a private driver (a private BLOB is used) I don't work with him.
> 

Could you please kindly give me some advise on how to download or install the private driver? Many thanks!

**Comment by 150balbes** [comment]
> I understand. Do you know whether its performance when playing back video in the web browser is better? Right now the main (only?) downside of using this as a desktop machine imho is that (FullHD fullscreen) video in the browser (e.g., YouTube) is almost unusable. But FullHD fullscreen video works well e.g., in OpenELEC.

If you want to have a full-screen 1080 video, use either the corresponding chip option (rk3399\s912\s922), or use specialized Libreelec or Android systems.



> Could you please kindly give me some advise on how to download or install the private driver?

I don't know that information.

**Comment by probonopd** [comment]
I can confirm that on a s912 based system video in the browser is much better, but the FPS in fullscreen mode are still not 100% satisfactory.

I wonder why it can be done butter smooth in "specialized Libreelec or Android systems" but apparently not (yet?) in normal Desktop Linux systems.

**Comment by rongi5** [comment]
stay developer.arm.com It has ARM private GPU drivers But I will not compile these drivers
