### ISSUE TITLE
GPIO/UART access once booted

### ISSUE THREAD

**Issue by ClosetMonkey** [150balbes/Amlogic_s905-kernel#3]
Not sure if this is the right place to post, but I would like to use the UART interface of my X96 mini in Linux userspace. Long story short I would like to use the GPIO for a dedicated serial link between the X96 and an arduino pro mini. How would this be possible?

**Comment by ClosetMonkey** [comment]
I would like low-level access to the RX/TX pins, but other docs that I've read hint that Armbian uses the GPIO for a serial terminal once booted. Is this true?

**Comment by isjerryxiao** [comment]
If what you want is just an UART, just stop getty@ttySX.service, and you'll be able to use /dev/ttySX to perform your serial connection.
To make it persistent, remove console=ttyS0 from your kernel cmdline and probably disable getty@ttyS0.service

**Comment by isjerryxiao** [comment]
Unless you compile and flash your own uboot, there's no way you can tell uboot not to write lines through the built-in serial.
