### ISSUE TITLE
Activate IFB for traffic shaping

### ISSUE THREAD

**Issue by amaury-d** [150balbes/Amlogic_s905-kernel#6]
Hello,

Please can you add `CONFIG_IFB=m` ( https://cateee.net/lkddb/web-lkddb/IFB.html ) to be able to use traffic shaping on s905 boxes ?

Thanks for your hard work btw

**Comment by 150balbes** [comment]
Sorry, I missed your message earlier. I'll see what I can do.

**Comment by 150balbes** [comment]
add ver Armbian 5.77 20190401
