### ISSUE TITLE
could you add bbr support for kernel 5.0 stable release ?

### ISSUE THREAD

**Issue by PsymonLi** [150balbes/Amlogic_s905-kernel#7]
No bbr support in kernel 5.0 rc8 version,could you add bbr support for kernel 5.0 stable release?thanks

**Comment by 150balbes** [comment]
Sorry, I didn't understand the question. What doesn't work and what should be added ? Write in more detail the essence of the problem.

**Comment by PsymonLi** [comment]
it's a kernel module named tcp_bbr,thanks

**Comment by 150balbes** [comment]
There are no such configurations in the kernel.

**Comment by isjerryxiao** [comment]
@150balbes CONFIG_TCP_CONG_BBR,  should be M

**Comment by 150balbes** [comment]
add Armbian 5.77 20190401
