### ISSUE TITLE
How to get uInitrd; How to compile uInitrd?

### ISSUE THREAD

**Issue by Hnmtc** [150balbes/Amlogic_s905-kernel#8]
How to get uInitrd;
How to compile uInitrd?

**Comment by zys1310992814** [comment]
1.using mkinitrd command to creat a initrd file, and you can config it to build your modules;
2.use uboot tools to add a head to this initrd;
3.enjoy it.

**Comment by Hnmtc** [comment]
thank you very much

**Comment by Hnmtc** [comment]
> 1.使用mkinitrd命令创建一个initrd文件，你可以配置它来构建你的模块; 
> 2.使用uboot工具向此initrd添加头部; 
> 3.享受它。

thank you very much
