### ISSUE TITLE
When Phicomm-n1 is under no load, the system load is around 2

### ISSUE THREAD

**Issue by Hnmtc** [150balbes/Amlogic_s905-kernel#9]
When Phicomm-n1 is under no load, the system load is around 2
Is there a patch that can be fixed?

**Comment by 150balbes** [comment]
It is not clear what system, what kernel. And you need to see what processes are running (that spends resources).

**Comment by Hnmtc** [comment]
load average: 2.46  2.43  2.37
System Debian
Kernel 5.0.0
irq/38-0.200908     CPU:  10%
kworker/0:0+eve    CPU: 2.6%
kworker/0:3-eve     CPU: 1.6%

**Comment by 150balbes** [comment]
> kworker/0:0+eve CPU: 2.6%

This element is associated with interrupts. There are recipes on the Internet how to determine which firmware the activity may be associated with and how to disable them.

**Comment by Hnmtc** [comment]
Return to normal after deleting the following code：
arch/arm64/boot/dts/amlogic/meson-gxl-s905d-p230.dts
/* 
interrupt-parent = <&gpio_intc>;
interrupts = <29 IRQ_TYPE_LEVEL_LOW>;
*/
